### ISSUE TITLE
 change the name from 'template' to a more meaningful one

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/bluesky-stomp#13]
It's a message bus client in the abstract
`template = MessagingTemplate.for_broker(Broker(host="localhost", port=61613))`

Another past refactor was done here :
https://github.com/DiamondLightSource/blueapi/pull/563/files#diff-0a751cf1fb152323956924e2914a2f7ef9d579830eacb06813ef98dd81fb8ace

**Comment by callumforrester** [comment]
Happy to change it, although I don't like `StompClient`; it's not a client but a wrapper around a third party client that provides helper methods for doing common tasks. Any ideas?

**Comment by stan-dot** [comment]
BlueStompClient? EventModelStompClient?

fwiw this whole repo might have been a part of https://github.com/bluesky/event-model

**Comment by callumforrester** [comment]
My objection is to the word "Client" specifically. 

Event-model has a very narrow scope, as do most other bluesky modules, the idea is to create this toolbox structure where you are free to pick and choose components that are useful to you:

![image](https://github.com/user-attachments/assets/8368dd97-401a-4228-9baa-2be2c670b59e)

**Comment by DiamondJoseph** [comment]
My 2 pence: `MessagingTemplate` is a `MessagingInterface` (or `Protocol`, but that word is heavily overloaded in messaging).

We may later want to support the case of a Template backed by multiple brokers for simulcast.

**Comment by stan-dot** [comment]
> the idea is to create this toolbox structure where you are free to pick and choose components that are useful to you

so far all adoption at DLS has been wholesale; blueapi + ophyd-async devices + eventmodel messaging.

the word *you* here means [bluesky stack user], what more do we know about this person? I don't have the domain-specific imagination for scenarios where someone would like to use one part but not the other. 

In a technical sense *the idea* you mention is a high decoupling of software components, which requires each to be abstract and generic. That does create some overhead, and we can postulate that there is a limit on how far can be the decoupling done - how coupled is the domain-specific data and flows.


> it's not a client but a wrapper around a third party client that provides helper methods for doing common tasks.

still the _role_ is plays is that of a *client* and whatever it does inside is, wrapper, or otherwise, is an implementation detail from an application developer perspective.

**Comment by callumforrester** [comment]
Hmm, I could be convinced of that. I'd accept a PR renaming it to `StompClient` or similar.
